CREATE TABLE IF NOT EXISTS `recognized_objects` (
	`ID`	INTEGER NOT NULL PRIMARY KEY UNIQUE,
	`Name`	TEXT NOT NULL,
	`Certainty`	NUMERIC,
	`Location`	TEXT
);
INSERT INTO 'recognized_objects' VALUES (0000, 'tench, Tinca tinca', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0001, 'goldfish, Carassius auratus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0002, 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0003, 'tiger shark, Galeocerdo cuvieri', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0004, 'hammerhead, hammerhead shark', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0005, 'electric ray, crampfish, numbfish, torpedo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0006, 'stingray', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0007, 'cock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0008, 'hen', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0009, 'ostrich, Struthio camelus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0010, 'brambling, Fringilla montifringilla', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0011, 'goldfinch, Carduelis carduelis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0012, 'house finch, linnet, Carpodacus mexicanus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0013, 'junco, snowbird', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0014, 'indigo bunting, indigo finch, indigo bird, Passerina cyanea', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0015, 'robin, American robin, Turdus migratorius', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0016, 'bulbul', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0017, 'jay', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0018, 'magpie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0019, 'chickadee', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0020, 'water ouzel, dipper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0021, 'kite', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0022, 'bald eagle, American eagle, Haliaeetus leucocephalus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0023, 'vulture', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0024, 'great grey owl, great gray owl, Strix nebulosa', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0025, 'European fire salamander, Salamandra salamandra', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0026, 'common newt, Triturus vulgaris', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0027, 'eft', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0028, 'spotted salamander, Ambystoma maculatum', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0029, 'axolotl, mud puppy, Ambystoma mexicanum', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0030, 'bullfrog, Rana catesbeiana', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0031, 'tree frog, tree-frog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0032, 'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0033, 'loggerhead, loggerhead turtle, Caretta caretta', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0034, 'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0035, 'mud turtle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0036, 'terrapin', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0037, 'box turtle, box tortoise', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0038, 'banded gecko', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0039, 'common iguana, iguana, Iguana iguana', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0040, 'American chameleon, anole, Anolis carolinensis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0041, 'whiptail, whiptail lizard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0042, 'agama', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0043, 'frilled lizard, Chlamydosaurus kingi', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0044, 'alligator lizard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0045, 'Gila monster, Heloderma suspectum', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0046, 'green lizard, Lacerta viridis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0047, 'African chameleon, Chamaeleo chamaeleon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0048, 'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0049, 'African crocodile, Nile crocodile, Crocodylus niloticus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0050, 'American alligator, Alligator mississipiensis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0051, 'triceratops', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0052, 'thunder snake, worm snake, Carphophis amoenus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0053, 'ringneck snake, ring-necked snake, ring snake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0054, 'hognose snake, puff adder, sand viper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0055, 'green snake, grass snake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0056, 'king snake, kingsnake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0057, 'garter snake, grass snake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0058, 'water snake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0059, 'vine snake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0060, 'night snake, Hypsiglena torquata', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0061, 'boa constrictor, Constrictor constrictor', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0062, 'rock python, rock snake, Python sebae', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0063, 'Indian cobra, Naja naja', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0064, 'green mamba', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0065, 'sea snake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0066, 'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0067, 'diamondback, diamondback rattlesnake, Crotalus adamanteus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0068, 'sidewinder, horned rattlesnake, Crotalus cerastes', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0069, 'trilobite', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0070, 'harvestman, daddy longlegs, Phalangium opilio', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0071, 'scorpion', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0072, 'black and gold garden spider, Argiope aurantia', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0073, 'barn spider, Araneus cavaticus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0074, 'garden spider, Aranea diademata', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0075, 'black widow, Latrodectus mactans', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0076, 'tarantula', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0077, 'wolf spider, hunting spider', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0078, 'tick', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0079, 'centipede', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0080, 'black grouse', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0081, 'ptarmigan', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0082, 'ruffed grouse, partridge, Bonasa umbellus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0083, 'prairie chicken, prairie grouse, prairie fowl', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0084, 'peacock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0085, 'quail', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0086, 'partridge', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0087, 'African grey, African gray, Psittacus erithacus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0088, 'macaw', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0089, 'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0090, 'lorikeet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0091, 'coucal', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0092, 'bee eater', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0093, 'hornbill', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0094, 'hummingbird', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0095, 'jacamar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0096, 'toucan', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0097, 'drake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0098, 'red-breasted merganser, Mergus serrator', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0099, 'goose', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0100, 'black swan, Cygnus atratus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0101, 'tusker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0102, 'echidna, spiny anteater, anteater', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0103, 'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0104, 'wallaby, brush kangaroo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0105, 'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0106, 'wombat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0107, 'jellyfish', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0108, 'sea anemone, anemone', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0109, 'brain coral', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0110, 'flatworm, platyhelminth', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0111, 'nematode, nematode worm, roundworm', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0112, 'conch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0113, 'snail', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0114, 'slug', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0115, 'sea slug, nudibranch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0116, 'chiton, coat-of-mail shell, sea cradle, polyplacophore', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0117, 'chambered nautilus, pearly nautilus, nautilus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0118, 'Dungeness crab, Cancer magister', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0119, 'rock crab, Cancer irroratus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0120, 'fiddler crab', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0121, 'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0122, 'American lobster, Northern lobster, Maine lobster, Homarus americanus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0123, 'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0124, 'crayfish, crawfish, crawdad, crawdaddy', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0125, 'hermit crab', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0126, 'isopod', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0127, 'white stork, Ciconia ciconia', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0128, 'black stork, Ciconia nigra', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0129, 'spoonbill', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0130, 'flamingo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0131, 'little blue heron, Egretta caerulea', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0132, 'American egret, great white heron, Egretta albus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0133, 'bittern', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0134, 'crane', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0135, 'limpkin, Aramus pictus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0136, 'European gallinule, Porphyrio porphyrio', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0137, 'American coot, marsh hen, mud hen, water hen, Fulica americana', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0138, 'bustard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0139, 'ruddy turnstone, Arenaria interpres', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0140, 'red-backed sandpiper, dunlin, Erolia alpina', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0141, 'redshank, Tringa totanus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0142, 'dowitcher', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0143, 'oystercatcher, oyster catcher', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0144, 'pelican', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0145, 'king penguin, Aptenodytes patagonica', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0146, 'albatross, mollymawk', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0147, 'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0148, 'killer whale, killer, orca, grampus, sea wolf, Orcinus orca', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0149, 'dugong, Dugong dugon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0150, 'sea lion', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0151, 'Chihuahua', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0152, 'Japanese spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0153, 'Maltese dog, Maltese terrier, Maltese', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0154, 'Pekinese, Pekingese, Peke', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0155, 'Shih-Tzu', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0156, 'Blenheim spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0157, 'papillon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0158, 'toy terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0159, 'Rhodesian ridgeback', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0160, 'Afghan hound, Afghan', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0161, 'basset, basset hound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0162, 'beagle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0163, 'bloodhound, sleuthhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0164, 'bluetick', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0165, 'black-and-tan coonhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0166, 'Walker hound, Walker foxhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0167, 'English foxhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0168, 'redbone', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0169, 'borzoi, Russian wolfhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0170, 'Irish wolfhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0171, 'Italian greyhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0172, 'whippet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0173, 'Ibizan hound, Ibizan Podenco', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0174, 'Norwegian elkhound, elkhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0175, 'otterhound, otter hound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0176, 'Saluki, gazelle hound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0177, 'Scottish deerhound, deerhound', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0178, 'Weimaraner', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0179, 'Staffordshire bullterrier, Staffordshire bull terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0180, 'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0181, 'Bedlington terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0182, 'Border terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0183, 'Kerry blue terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0184, 'Irish terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0185, 'Norfolk terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0186, 'Norwich terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0187, 'Yorkshire terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0188, 'wire-haired fox terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0189, 'Lakeland terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0190, 'Sealyham terrier, Sealyham', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0191, 'Airedale, Airedale terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0192, 'cairn, cairn terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0193, 'Australian terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0194, 'Dandie Dinmont, Dandie Dinmont terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0195, 'Boston bull, Boston terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0196, 'miniature schnauzer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0197, 'giant schnauzer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0198, 'standard schnauzer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0199, 'Scotch terrier, Scottish terrier, Scottie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0200, 'Tibetan terrier, chrysanthemum dog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0201, 'silky terrier, Sydney silky', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0202, 'soft-coated wheaten terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0203, 'West Highland white terrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0204, 'Lhasa, Lhasa apso', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0205, 'flat-coated retriever', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0206, 'curly-coated retriever', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0207, 'golden retriever', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0208, 'Labrador retriever', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0209, 'Chesapeake Bay retriever', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0210, 'German short-haired pointer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0211, 'vizsla, Hungarian pointer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0212, 'English setter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0213, 'Irish setter, red setter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0214, 'Gordon setter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0215, 'Brittany spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0216, 'clumber, clumber spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0217, 'English springer, English springer spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0218, 'Welsh springer spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0219, 'cocker spaniel, English cocker spaniel, cocker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0220, 'Sussex spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0221, 'Irish water spaniel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0222, 'kuvasz', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0223, 'schipperke', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0224, 'groenendael', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0225, 'malinois', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0226, 'briard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0227, 'kelpie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0228, 'komondor', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0229, 'Old English sheepdog, bobtail', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0230, 'Shetland sheepdog, Shetland sheep dog, Shetland', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0231, 'collie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0232, 'Border collie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0233, 'Bouvier des Flandres, Bouviers des Flandres', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0234, 'Rottweiler', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0235, 'German shepherd, German shepherd dog, German police dog, alsatian', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0236, 'Doberman, Doberman pinscher', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0237, 'miniature pinscher', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0238, 'Greater Swiss Mountain dog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0239, 'Bernese mountain dog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0240, 'Appenzeller', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0241, 'EntleBucher', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0242, 'boxer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0243, 'bull mastiff', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0244, 'Tibetan mastiff', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0245, 'French bulldog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0246, 'Great Dane', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0247, 'Saint Bernard, St Bernard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0248, 'Eskimo dog, husky', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0249, 'malamute, malemute, Alaskan malamute', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0250, 'Siberian husky', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0251, 'dalmatian, coach dog, carriage dog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0252, 'affenpinscher, monkey pinscher, monkey dog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0253, 'basenji', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0254, 'pug, pug-dog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0255, 'Leonberg', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0256, 'Newfoundland, Newfoundland dog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0257, 'Great Pyrenees', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0258, 'Samoyed, Samoyede', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0259, 'Pomeranian', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0260, 'chow, chow chow', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0261, 'keeshond', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0262, 'Brabancon griffon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0263, 'Pembroke, Pembroke Welsh corgi', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0264, 'Cardigan, Cardigan Welsh corgi', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0265, 'toy poodle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0266, 'miniature poodle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0267, 'standard poodle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0268, 'Mexican hairless', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0269, 'timber wolf, grey wolf, gray wolf, Canis lupus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0270, 'white wolf, Arctic wolf, Canis lupus tundrarum', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0271, 'red wolf, maned wolf, Canis rufus, Canis niger', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0272, 'coyote, prairie wolf, brush wolf, Canis latrans', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0273, 'dingo, warrigal, warragal, Canis dingo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0274, 'dhole, Cuon alpinus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0275, 'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0276, 'hyena, hyaena', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0277, 'red fox, Vulpes vulpes', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0278, 'kit fox, Vulpes macrotis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0279, 'Arctic fox, white fox, Alopex lagopus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0280, 'grey fox, gray fox, Urocyon cinereoargenteus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0281, 'tabby, tabby cat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0282, 'tiger cat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0283, 'Persian cat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0284, 'Siamese cat, Siamese', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0285, 'Egyptian cat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0286, 'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0287, 'lynx, catamount', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0288, 'leopard, Panthera pardus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0289, 'snow leopard, ounce, Panthera uncia', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0290, 'jaguar, panther, Panthera onca, Felis onca', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0291, 'lion, king of beasts, Panthera leo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0292, 'tiger, Panthera tigris', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0293, 'cheetah, chetah, Acinonyx jubatus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0294, 'brown bear, bruin, Ursus arctos', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0295, 'American black bear, black bear, Ursus americanus, Euarctos americanus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0296, 'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0297, 'sloth bear, Melursus ursinus, Ursus ursinus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0298, 'mongoose', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0299, 'meerkat, mierkat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0300, 'tiger beetle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0301, 'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0302, 'ground beetle, carabid beetle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0303, 'long-horned beetle, longicorn, longicorn beetle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0304, 'leaf beetle, chrysomelid', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0305, 'dung beetle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0306, 'rhinoceros beetle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0307, 'weevil', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0308, 'fly', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0309, 'bee', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0310, 'ant, emmet, pismire', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0311, 'grasshopper, hopper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0312, 'cricket', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0313, 'walking stick, walkingstick, stick insect', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0314, 'cockroach, roach', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0315, 'mantis, mantid', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0316, 'cicada, cicala', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0317, 'leafhopper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0318, 'lacewing, lacewing fly', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0319, "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0320, 'damselfly', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0321, 'admiral', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0322, 'ringlet, ringlet butterfly', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0323, 'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0324, 'cabbage butterfly', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0325, 'sulphur butterfly, sulfur butterfly', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0326, 'lycaenid, lycaenid butterfly', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0327, 'starfish, sea star', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0328, 'sea urchin', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0329, 'sea cucumber, holothurian', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0330, 'wood rabbit, cottontail, cottontail rabbit', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0331, 'hare', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0332, 'Angora, Angora rabbit', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0333, 'hamster', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0334, 'porcupine, hedgehog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0335, 'fox squirrel, eastern fox squirrel, Sciurus niger', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0336, 'marmot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0337, 'beaver', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0338, 'guinea pig, Cavia cobaya', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0339, 'sorrel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0340, 'zebra', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0341, 'hog, pig, grunter, squealer, Sus scrofa', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0342, 'wild boar, boar, Sus scrofa', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0343, 'warthog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0344, 'hippopotamus, hippo, river horse, Hippopotamus amphibius', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0345, 'ox', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0346, 'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0347, 'bison', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0348, 'ram, tup', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0349, 'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0350, 'ibex, Capra ibex', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0351, 'hartebeest', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0352, 'impala, Aepyceros melampus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0353, 'gazelle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0354, 'Arabian camel, dromedary, Camelus dromedarius', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0355, 'llama', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0356, 'weasel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0357, 'mink', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0358, 'polecat, fitch, foulmart, foumart, Mustela putorius', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0359, 'black-footed ferret, ferret, Mustela nigripes', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0360, 'otter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0361, 'skunk, polecat, wood pussy', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0362, 'badger', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0363, 'armadillo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0364, 'three-toed sloth, ai, Bradypus tridactylus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0365, 'orangutan, orang, orangutang, Pongo pygmaeus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0366, 'gorilla, Gorilla gorilla', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0367, 'chimpanzee, chimp, Pan troglodytes', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0368, 'gibbon, Hylobates lar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0369, 'siamang, Hylobates syndactylus, Symphalangus syndactylus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0370, 'guenon, guenon monkey', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0371, 'patas, hussar monkey, Erythrocebus patas', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0372, 'baboon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0373, 'macaque', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0374, 'langur', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0375, 'colobus, colobus monkey', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0376, 'proboscis monkey, Nasalis larvatus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0377, 'marmoset', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0378, 'capuchin, ringtail, Cebus capucinus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0379, 'howler monkey, howler', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0380, 'titi, titi monkey', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0381, 'spider monkey, Ateles geoffroyi', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0382, 'squirrel monkey, Saimiri sciureus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0383, 'Madagascar cat, ring-tailed lemur, Lemur catta', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0384, 'indri, indris, Indri indri, Indri brevicaudatus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0385, 'Indian elephant, Elephas maximus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0386, 'African elephant, Loxodonta africana', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0387, 'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0388, 'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0389, 'barracouta, snoek', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0390, 'eel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0391, 'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0392, 'rock beauty, Holocanthus tricolor', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0393, 'anemone fish', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0394, 'sturgeon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0395, 'gar, garfish, garpike, billfish, Lepisosteus osseus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0396, 'lionfish', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0397, 'puffer, pufferfish, blowfish, globefish', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0398, 'abacus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0399, 'abaya', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0400, "academic gown, academic robe, judge's robe", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0401, 'accordion, piano accordion, squeeze box', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0402, 'acoustic guitar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0403, 'aircraft carrier, carrier, flattop, attack aircraft carrier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0404, 'airliner', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0405, 'airship, dirigible', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0406, 'altar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0407, 'ambulance', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0408, 'amphibian, amphibious vehicle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0409, 'analog clock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0410, 'apiary, bee house', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0411, 'apron', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0412, 'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0413, 'assault rifle, assault gun', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0414, 'backpack, back pack, knapsack, packsack, rucksack, haversack', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0415, 'bakery, bakeshop, bakehouse', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0416, 'balance beam, beam', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0417, 'balloon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0418, 'ballpoint, ballpoint pen, ballpen, Biro', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0419, 'Band Aid', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0420, 'banjo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0421, 'bannister, banister, balustrade, balusters, handrail', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0422, 'barbell', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0423, 'barber chair', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0424, 'barbershop', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0425, 'barn', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0426, 'barometer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0427, 'barrel, cask', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0428, 'barrow, garden cart, lawn cart, wheelbarrow', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0429, 'baseball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0430, 'basketball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0431, 'bassinet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0432, 'bassoon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0433, 'bathing cap, swimming cap', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0434, 'bath towel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0435, 'bathtub, bathing tub, bath, tub', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0436, 'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0437, 'beacon, lighthouse, beacon light, pharos', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0438, 'beaker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0439, 'bearskin, busby, shako', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0440, 'beer bottle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0441, 'beer glass', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0442, 'bell cote, bell cot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0443, 'bib', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0444, 'bicycle-built-for-two, tandem bicycle, tandem', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0445, 'bikini, two-piece', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0446, 'binder, ring-binder', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0447, 'binoculars, field glasses, opera glasses', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0448, 'birdhouse', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0449, 'boathouse', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0450, 'bobsled, bobsleigh, bob', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0451, 'bolo tie, bolo, bola tie, bola', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0452, 'bonnet, poke bonnet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0453, 'bookcase', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0454, 'bookshop, bookstore, bookstall', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0455, 'bottlecap', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0456, 'bow', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0457, 'bow tie, bow-tie, bowtie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0458, 'brass, memorial tablet, plaque', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0459, 'brassiere, bra, bandeau', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0460, 'breakwater, groin, groyne, mole, bulwark, seawall, jetty', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0461, 'breastplate, aegis, egis', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0462, 'broom', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0463, 'bucket, pail', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0464, 'buckle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0465, 'bulletproof vest', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0466, 'bullet train, bullet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0467, 'butcher shop, meat market', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0468, 'cab, hack, taxi, taxicab', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0469, 'caldron, cauldron', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0470, 'candle, taper, wax light', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0471, 'cannon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0472, 'canoe', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0473, 'can opener, tin opener', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0474, 'cardigan', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0475, 'car mirror', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0476, 'carousel, carrousel, merry-go-round, roundabout, whirligig', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0477, "carpenter's kit, tool kit", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0478, 'carton', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0479, 'car wheel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0480, 'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0481, 'cassette', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0482, 'cassette player', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0483, 'castle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0484, 'catamaran', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0485, 'CD player', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0486, 'cello, violoncello', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0487, 'cellular telephone, cellular phone, cellphone, cell, mobile phone', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0488, 'chain', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0489, 'chainlink fence', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0490, 'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0491, 'chain saw, chainsaw', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0492, 'chest', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0493, 'chiffonier, commode', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0494, 'chime, bell, gong', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0495, 'china cabinet, china closet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0496, 'Christmas stocking', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0497, 'church, church building', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0498, 'cinema, movie theater, movie theatre, movie house, picture palace', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0499, 'cleaver, meat cleaver, chopper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0500, 'cliff dwelling', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0501, 'cloak', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0502, 'clog, geta, patten, sabot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0503, 'cocktail shaker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0504, 'coffee mug', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0505, 'coffeepot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0506, 'coil, spiral, volute, whorl, helix', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0507, 'combination lock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0508, 'computer keyboard, keypad', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0509, 'confectionery, confectionary, candy store', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0510, 'container ship, containership, container vessel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0511, 'convertible', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0512, 'corkscrew, bottle screw', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0513, 'cornet, horn, trumpet, trump', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0514, 'cowboy boot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0515, 'cowboy hat, ten-gallon hat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0516, 'cradle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0517, 'crane', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0518, 'crash helmet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0519, 'crate', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0520, 'crib, cot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0521, 'Crock Pot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0522, 'croquet ball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0523, 'crutch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0524, 'cuirass', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0525, 'dam, dike, dyke', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0526, 'desk', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0527, 'desktop computer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0528, 'dial telephone, dial phone', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0529, 'diaper, nappy, napkin', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0530, 'digital clock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0531, 'digital watch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0532, 'dining table, board', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0533, 'dishrag, dishcloth', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0534, 'dishwasher, dish washer, dishwashing machine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0535, 'disk brake, disc brake', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0536, 'dock, dockage, docking facility', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0537, 'dogsled, dog sled, dog sleigh', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0538, 'dome', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0539, 'doormat, welcome mat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0540, 'drilling platform, offshore rig', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0541, 'drum, membranophone, tympan', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0542, 'drumstick', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0543, 'dumbbell', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0544, 'Dutch oven', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0545, 'electric fan, blower', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0546, 'electric guitar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0547, 'electric locomotive', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0548, 'entertainment center', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0549, 'envelope', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0550, 'espresso maker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0551, 'face powder', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0552, 'feather boa, boa', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0553, 'file, file cabinet, filing cabinet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0554, 'fireboat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0555, 'fire engine, fire truck', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0556, 'fire screen, fireguard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0557, 'flagpole, flagstaff', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0558, 'flute, transverse flute', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0559, 'folding chair', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0560, 'football helmet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0561, 'forklift', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0562, 'fountain', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0563, 'fountain pen', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0564, 'four-poster', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0565, 'freight car', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0566, 'French horn, horn', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0567, 'frying pan, frypan, skillet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0568, 'fur coat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0569, 'garbage truck, dustcart', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0570, 'gasmask, respirator, gas helmet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0571, 'gas pump, gasoline pump, petrol pump, island dispenser', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0572, 'goblet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0573, 'go-kart', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0574, 'golf ball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0575, 'golfcart, golf cart', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0576, 'gondola', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0577, 'gong, tam-tam', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0578, 'gown', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0579, 'grand piano, grand', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0580, 'greenhouse, nursery, glasshouse', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0581, 'grille, radiator grille', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0582, 'grocery store, grocery, food market, market', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0583, 'guillotine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0584, 'hair slide', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0585, 'hair spray', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0586, 'half track', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0587, 'hammer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0588, 'hamper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0589, 'hand blower, blow dryer, blow drier, hair dryer, hair drier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0590, 'hand-held computer, hand-held microcomputer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0591, 'handkerchief, hankie, hanky, hankey', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0592, 'hard disc, hard disk, fixed disk', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0593, 'harmonica, mouth organ, harp, mouth harp', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0594, 'harp', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0595, 'harvester, reaper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0596, 'hatchet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0597, 'holster', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0598, 'home theater, home theatre', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0599, 'honeycomb', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0600, 'hook, claw', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0601, 'hoopskirt, crinoline', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0602, 'horizontal bar, high bar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0603, 'horse cart, horse-cart', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0604, 'hourglass', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0605, 'iPod', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0606, 'iron, smoothing iron', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0607, "jack-o'-lantern", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0608, 'jean, blue jean, denim', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0609, 'jeep, landrover', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0610, 'jersey, T-shirt, tee shirt', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0611, 'jigsaw puzzle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0612, 'jinrikisha, ricksha, rickshaw', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0613, 'joystick', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0614, 'kimono', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0615, 'knee pad', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0616, 'knot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0617, 'lab coat, laboratory coat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0618, 'ladle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0619, 'lampshade, lamp shade', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0620, 'laptop, laptop computer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0621, 'lawn mower, mower', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0622, 'lens cap, lens cover', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0623, 'letter opener, paper knife, paperknife', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0624, 'library', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0625, 'lifeboat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0626, 'lighter, light, igniter, ignitor', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0627, 'limousine, limo', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0628, 'liner, ocean liner', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0629, 'lipstick, lip rouge', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0630, 'Loafer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0631, 'lotion', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0632, 'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0633, "loupe, jeweler's loupe", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0634, 'lumbermill, sawmill', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0635, 'magnetic compass', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0636, 'mailbag, postbag', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0637, 'mailbox, letter box', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0638, 'maillot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0639, 'maillot, tank suit', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0640, 'manhole cover', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0641, 'maraca', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0642, 'marimba, xylophone', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0643, 'mask', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0644, 'matchstick', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0645, 'maypole', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0646, 'maze, labyrinth', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0647, 'measuring cup', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0648, 'medicine chest, medicine cabinet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0649, 'megalith, megalithic structure', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0650, 'microphone, mike', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0651, 'microwave, microwave oven', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0652, 'military uniform', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0653, 'milk can', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0654, 'minibus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0655, 'miniskirt, mini', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0656, 'minivan', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0657, 'missile', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0658, 'mitten', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0659, 'mixing bowl', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0660, 'mobile home, manufactured home', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0661, 'Model T', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0662, 'modem', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0663, 'monastery', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0664, 'monitor', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0665, 'moped', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0666, 'mortar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0667, 'mortarboard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0668, 'mosque', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0669, 'mosquito net', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0670, 'motor scooter, scooter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0671, 'mountain bike, all-terrain bike, off-roader', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0672, 'mountain tent', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0673, 'mouse, computer mouse', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0674, 'mousetrap', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0675, 'moving van', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0676, 'muzzle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0677, 'nail', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0678, 'neck brace', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0679, 'necklace', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0680, 'nipple', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0681, 'notebook, notebook computer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0682, 'obelisk', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0683, 'oboe, hautboy, hautbois', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0684, 'ocarina, sweet potato', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0685, 'odometer, hodometer, mileometer, milometer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0686, 'oil filter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0687, 'organ, pipe organ', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0688, 'oscilloscope, scope, cathode-ray oscilloscope, CRO', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0689, 'overskirt', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0690, 'oxcart', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0691, 'oxygen mask', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0692, 'packet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0693, 'paddle, boat paddle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0694, 'paddlewheel, paddle wheel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0695, 'padlock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0696, 'paintbrush', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0697, "pajama, pyjama, pj's, jammies", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0698, 'palace', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0699, 'panpipe, pandean pipe, syrinx', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0700, 'paper towel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0701, 'parachute, chute', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0702, 'parallel bars, bars', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0703, 'park bench', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0704, 'parking meter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0705, 'passenger car, coach, carriage', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0706, 'patio, terrace', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0707, 'pay-phone, pay-station', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0708, 'pedestal, plinth, footstall', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0709, 'pencil box, pencil case', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0710, 'pencil sharpener', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0711, 'perfume, essence', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0712, 'Petri dish', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0713, 'photocopier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0714, 'pick, plectrum, plectron', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0715, 'pickelhaube', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0716, 'picket fence, paling', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0717, 'pickup, pickup truck', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0718, 'pier', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0719, 'piggy bank, penny bank', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0720, 'pill bottle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0721, 'pillow', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0722, 'ping-pong ball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0723, 'pinwheel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0724, 'pirate, pirate ship', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0725, 'pitcher, ewer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0726, "plane, carpenter's plane, woodworking plane", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0727, 'planetarium', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0728, 'plastic bag', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0729, 'plate rack', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0730, 'plow, plough', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0731, "plunger, plumber's helper", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0732, 'Polaroid camera, Polaroid Land camera', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0733, 'pole', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0734, 'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0735, 'poncho', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0736, 'pool table, billiard table, snooker table', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0737, 'pop bottle, soda bottle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0738, 'pot, flowerpot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0739, "potter's wheel", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0740, 'power drill', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0741, 'prayer rug, prayer mat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0742, 'printer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0743, 'prison, prison house', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0744, 'projectile, missile', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0745, 'projector', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0746, 'puck, hockey puck', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0747, 'punching bag, punch bag, punching ball, punchball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0748, 'purse', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0749, 'quill, quill pen', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0750, 'quilt, comforter, comfort, puff', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0751, 'racer, race car, racing car', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0752, 'racket, racquet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0753, 'radiator', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0754, 'radio, wireless', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0755, 'radio telescope, radio reflector', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0756, 'rain barrel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0757, 'recreational vehicle, RV, R.V.', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0758, 'reel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0759, 'reflex camera', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0760, 'refrigerator, icebox', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0761, 'remote control, remote', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0762, 'restaurant, eating house, eating place, eatery', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0763, 'revolver, six-gun, six-shooter', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0764, 'rifle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0765, 'rocking chair, rocker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0766, 'rotisserie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0767, 'rubber eraser, rubber, pencil eraser', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0768, 'rugby ball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0769, 'rule, ruler', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0770, 'running shoe', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0771, 'safe', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0772, 'safety pin', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0773, 'saltshaker, salt shaker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0774, 'sandal', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0775, 'sarong', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0776, 'sax, saxophone', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0777, 'scabbard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0778, 'scale, weighing machine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0779, 'school bus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0780, 'schooner', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0781, 'scoreboard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0782, 'screen, CRT screen', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0783, 'screw', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0784, 'screwdriver', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0785, 'seat belt, seatbelt', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0786, 'sewing machine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0787, 'shield, buckler', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0788, 'shoe shop, shoe-shop, shoe store', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0789, 'shoji', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0790, 'shopping basket', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0791, 'shopping cart', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0792, 'shovel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0793, 'shower cap', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0794, 'shower curtain', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0795, 'ski', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0796, 'ski mask', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0797, 'sleeping bag', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0798, 'slide rule, slipstick', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0799, 'sliding door', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0800, 'slot, one-armed bandit', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0801, 'snorkel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0802, 'snowmobile', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0803, 'snowplow, snowplough', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0804, 'soap dispenser', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0805, 'soccer ball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0806, 'sock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0807, 'solar dish, solar collector, solar furnace', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0808, 'sombrero', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0809, 'soup bowl', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0810, 'space bar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0811, 'space heater', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0812, 'space shuttle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0813, 'spatula', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0814, 'speedboat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0815, "spider web, spider's web", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0816, 'spindle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0817, 'sports car, sport car', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0818, 'spotlight, spot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0819, 'stage', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0820, 'steam locomotive', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0821, 'steel arch bridge', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0822, 'steel drum', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0823, 'stethoscope', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0824, 'stole', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0825, 'stone wall', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0826, 'stopwatch, stop watch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0827, 'stove', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0828, 'strainer', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0829, 'streetcar, tram, tramcar, trolley, trolley car', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0830, 'stretcher', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0831, 'studio couch, day bed', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0832, 'stupa, tope', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0833, 'submarine, pigboat, sub, U-boat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0834, 'suit, suit of clothes', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0835, 'sundial', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0836, 'sunglass', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0837, 'sunglasses, dark glasses, shades', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0838, 'sunscreen, sunblock, sun blocker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0839, 'suspension bridge', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0840, 'swab, swob, mop', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0841, 'sweatshirt', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0842, 'swimming trunks, bathing trunks', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0843, 'swing', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0844, 'switch, electric switch, electrical switch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0845, 'syringe', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0846, 'table lamp', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0847, 'tank, army tank, armored combat vehicle, armoured combat vehicle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0848, 'tape player', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0849, 'teapot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0850, 'teddy, teddy bear', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0851, 'television, television system', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0852, 'tennis ball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0853, 'thatch, thatched roof', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0854, 'theater curtain, theatre curtain', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0855, 'thimble', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0856, 'thresher, thrasher, threshing machine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0857, 'throne', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0858, 'tile roof', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0859, 'toaster', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0860, 'tobacco shop, tobacconist shop, tobacconist', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0861, 'toilet seat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0862, 'torch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0863, 'totem pole', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0864, 'tow truck, tow car, wrecker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0865, 'toyshop', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0866, 'tractor', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0867, 'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0868, 'tray', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0869, 'trench coat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0870, 'tricycle, trike, velocipede', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0871, 'trimaran', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0872, 'tripod', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0873, 'triumphal arch', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0874, 'trolleybus, trolley coach, trackless trolley', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0875, 'trombone', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0876, 'tub, vat', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0877, 'turnstile', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0878, 'typewriter keyboard', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0879, 'umbrella', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0880, 'unicycle, monocycle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0881, 'upright, upright piano', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0882, 'vacuum, vacuum cleaner', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0883, 'vase', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0884, 'vault', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0885, 'velvet', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0886, 'vending machine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0887, 'vestment', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0888, 'viaduct', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0889, 'violin, fiddle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0890, 'volleyball', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0891, 'waffle iron', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0892, 'wall clock', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0893, 'wallet, billfold, notecase, pocketbook', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0894, 'wardrobe, closet, press', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0895, 'warplane, military plane', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0896, 'washbasin, handbasin, washbowl, lavabo, wash-hand basin', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0897, 'washer, automatic washer, washing machine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0898, 'water bottle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0899, 'water jug', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0900, 'water tower', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0901, 'whiskey jug', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0902, 'whistle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0903, 'wig', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0904, 'window screen', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0905, 'window shade', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0906, 'Windsor tie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0907, 'wine bottle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0908, 'wing', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0909, 'wok', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0910, 'wooden spoon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0911, 'wool, woolen, woollen', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0912, 'worm fence, snake fence, snake-rail fence, Virginia fence', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0913, 'wreck', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0914, 'yawl', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0915, 'yurt', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0916, 'web site, website, internet site, site', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0917, 'comic book', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0918, 'crossword puzzle, crossword', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0919, 'street sign', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0920, 'traffic light, traffic signal, stoplight', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0921, 'book jacket, dust cover, dust jacket, dust wrapper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0922, 'menu', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0923, 'plate', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0924, 'guacamole', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0925, 'consomme', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0926, 'hot pot, hotpot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0927, 'trifle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0928, 'ice cream, icecream', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0929, 'ice lolly, lolly, lollipop, popsicle', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0930, 'French loaf', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0931, 'bagel, beigel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0932, 'pretzel', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0933, 'cheeseburger', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0934, 'hotdog, hot dog, red hot', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0935, 'mashed potato', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0936, 'head cabbage', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0937, 'broccoli', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0938, 'cauliflower', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0939, 'zucchini, courgette', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0940, 'spaghetti squash', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0941, 'acorn squash', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0942, 'butternut squash', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0943, 'cucumber, cuke', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0944, 'artichoke, globe artichoke', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0945, 'bell pepper', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0946, 'cardoon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0947, 'mushroom', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0948, 'Granny Smith', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0949, 'strawberry', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0950, 'orange', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0951, 'lemon', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0952, 'fig', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0953, 'pineapple, ananas', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0954, 'banana', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0955, 'jackfruit, jak, jack', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0956, 'custard apple', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0957, 'pomegranate', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0958, 'hay', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0959, 'carbonara', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0960, 'chocolate sauce, chocolate syrup', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0961, 'dough', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0962, 'meat loaf, meatloaf', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0963, 'pizza, pizza pie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0964, 'potpie', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0965, 'burrito', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0966, 'red wine', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0967, 'espresso', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0968, 'cup', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0969, 'eggnog', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0970, 'alp', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0971, 'bubble', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0972, 'cliff, drop, drop-off', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0973, 'coral reef', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0974, 'geyser', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0975, 'lakeside, lakeshore', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0976, 'promontory, headland, head, foreland', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0977, 'sandbar, sand bar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0978, 'seashore, coast, seacoast, sea-coast', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0979, 'valley, vale', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0980, 'volcano', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0981, 'ballplayer, baseball player', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0982, 'groom, bridegroom', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0983, 'scuba diver', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0984, 'rapeseed', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0985, 'daisy', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0986, "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum", 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0987, 'corn', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0988, 'acorn', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0989, 'hip, rose hip, rosehip', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0990, 'buckeye, horse chestnut, conker', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0991, 'coral fungus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0992, 'agaric', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0993, 'gyromitra', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0994, 'stinkhorn, carrion fungus', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0995, 'earthstar', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0996, 'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0997, 'bolete', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0998, 'ear, spike, capitulum', 0, NULL);
INSERT INTO 'recognized_objects' VALUES (0999, 'toilet tissue, toilet paper, bathroom tissue', 0, NULL);
COMMIT;